import {
  saveJournalEntry, getTodayConversationId, getConversationMessages,
  getTodayMoodEntries, getLastSleepEntry, getActiveGoals, getTodayHabits,
  getTodayScreenTime, saveJournalEntry as saveJournal,
} from './database';
import { generateDailyJournal } from './brain';
import { getTopAppsToday, getTotalScreenTimeToday } from './screenReader';

export async function generateDailySummary(): Promise<any> {
  const conversationId = await getTodayConversationId();
  const messages = await getConversationMessages(conversationId);
  const todayMoods = await getTodayMoodEntries();
  const todaySleep = await getLastSleepEntry();
  const goals = await getActiveGoals();
  const habits = await getTodayHabits();
  const screenTimeMs = getTotalScreenTimeToday();
  const topApps = getTopAppsToday(5);
  const completedGoals = goals.filter((g: any) => g.progress >= 100);

  return {
    date: new Date().toISOString().split('T')[0],
    conversationsCount: 1,
    messagesCount: messages.length,
    mood: todayMoods[0]?.primary_emotion || 'neutral',
    moodScore: todayMoods[0]?.score || 5,
    sleepHours: todaySleep?.duration || 0,
    sleepQuality: todaySleep?.quality || 0,
    steps: 0,
    screenTimeMinutes: Math.round(screenTimeMs / 60000),
    goalsCompleted: completedGoals.length,
    goalsTotal: goals.length,
    topApps,
    highlights: extractHighlights(messages),
  };
}

function extractHighlights(messages: any[]): string[] {
  const highlights: string[] = [];
  messages.forEach((msg: any) => {
    if (msg.role === 'user' && msg.content.length > 20) {
      const content = msg.content.toLowerCase();
      if (content.includes('goal') || content.includes('achieved') || content.includes('finished') ||
          content.includes('completed') || content.includes('proud') || content.includes('breakthrough')) {
        highlights.push(msg.content);
      }
    }
  });
  return highlights.slice(0, 5);
}

export async function writeAutoJournal(): Promise<string> {
  await generateDailyJournal();
  return 'Journal generated by AXIS.';
}

export function calculateProductivityScore(summary: any): number {
  let score = 50;
  const moodScores: Record<string, number> = { motivated: 15, fine: 10, neutral: 5, tired: -5, stressed: -10, down: -15 };
  score += moodScores[summary.mood] || 0;
  if (summary.sleepHours >= 7) score += 10;
  else if (summary.sleepHours < 5) score -= 10;
  if (summary.goalsTotal > 0) score += Math.round((summary.goalsCompleted / summary.goalsTotal) * 15);
  if (summary.screenTimeMinutes > 360) score -= 10;
  return Math.max(0, Math.min(100, score));
}
